import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import { userService } from '../services/authorization.js';
import { LAMBDA_RESP } from '../lib/constants'
import FORM from '../Forms/join_group_login'

export async function getServerSideProps({req, res}) {
    
    const {email, token} = userService.getEmailFromToken({req, res});
    const group_id = req.url.match("[0-9a-z\-]+$")[0];
    if (email == null || group_id == "") {
        return {
            props:{
                groupId : group_id
            },
            redirect : {permanent: false,
                destination: "/"}
        }
    }

    const result = await userService.addUserToGroup(email, group_id);
    if (result == LAMBDA_RESP.SUCCESS) {
        // return {
        //     props:{},
        //     redirect : {permanent: false,
        //         destination: "../Groups/" + group_id}
        // }
        return {
            props : { groupId : group_id }
        }
    } else if (result == LAMBDA_RESP.INVALID || result == LAMBDA_RESP.ERROR) {
        return {
            props: {
                groupId : null
            }
        }
    }


}


export default function JoinGroup({groupId}) {
    return (
        <>
        
        <Head>
            <title>Join Group</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <header className={styles.header}>
                <Image
                    src = "/billmates_logo_trans.png"
                    alt={"Billmates Logo"}
                    width={500}
                    height={500}
                ></Image>
            </header>
    
          <main className = {styles.main}>
    
          <div className= {styles.position_box}>
    
          <FORM groupId={groupId}></FORM>
    
          </div>
    
          </main>
    
        </> 
      )
}