import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Register from './forms/register_form'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  
  
  
  return (
    <>
    
    <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        {/* change to just name with white background */}
            <Image
                src = "/billmates_logo_trans.png"
                alt={"Billmates Logo"}
                width={500}
                height={500}
            ></Image>
        </header>
      <main className = {styles.main}>
      <div className= {styles.position_box}>

      <Register></Register>

      </div>

      </main>

    </>



    
  )
}